### ISSUE TITLE
Arduino Due Host

### ISSUE THREAD

**Issue by Lucius0806** [arduino-libraries/USBHost#41]
I want to use the USBHost library to create a USB host in arduino due, and a usb device in arduino uno. then perform communication between them.. 
[USB_connect.xlsx](https://github.com/arduino-libraries/USBHost/files/12483090/USB_connect.xlsx)

**Comment by per1234** [comment]
Hi @Lucius0806. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
