### ISSUE TITLE
Can this library work with esp8266 or ep32

### ISSUE THREAD

**Issue by kenkit** [arduino-libraries/USBHost#50]
Hi, Since the USB host shield library supports esp8266 can this also be used on the esp8266 ?

**Comment by per1234** [comment]
Hi @kenkit. Thanks for your interest in this open source project.

I see that the information you requested is already documented in the readme so no action is required on our part to resolve this:

https://github.com/arduino-libraries/USBHost#usbhost-library-for-arduino

> The USBHost library allows an Arduino Due board to appear as a USB host
